######################################################################
# Automatically generated by qmake (1.07a) Sat May 9 11:40:02 2015
######################################################################

TEMPLATE = app

TARGET = labyrinth2015_gui

LIBS += build/core.so
PRE_TARGETDEPS += build/core.so